---
  language: go
  sudo: false
  notifications:
    email: false
  go:
    - 1.6
    - 1.7
    - 1.8
    - tip
  install:
    - go get github.com/Masterminds/glide
    - go get github.com/golang/lint/golint
    - $GOPATH/bin/glide install
  script:
    - go vet $($GOPATH/bin/glide nv)
    - test -z "$(golint $($(GOPATH/bin/glide nv)) | tee /dev/stderr)"
    - test -z "$(gofmt -s -l . | grep -E '^[^(vendor)]' | tee /dev/stderr)"
    - go test -v $($GOPATH/bin/glide nv)
